/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.widgets;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WidgetStateInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WidgetStateInfoTests
    {
        // TODO uncomment below to declare an instance variable for WidgetStateInfo
        //private WidgetStateInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WidgetStateInfo
            //instance = new WidgetStateInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WidgetStateInfo
        /// </summary>
        [Test]
        public void WidgetStateInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WidgetStateInfo
            //Assert.IsInstanceOfType<WidgetStateInfo> (instance, "variable 'instance' is a WidgetStateInfo");
        }


        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'WidgetInActiveInfo'
        /// </summary>
        [Test]
        public void WidgetInActiveInfoTest()
        {
            // TODO unit test for the property 'WidgetInActiveInfo'
        }

    }

}
