/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.widgets;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WidgetAgreements
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WidgetAgreementsTests
    {
        // TODO uncomment below to declare an instance variable for WidgetAgreements
        //private WidgetAgreements instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WidgetAgreements
            //instance = new WidgetAgreements();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WidgetAgreements
        /// </summary>
        [Test]
        public void WidgetAgreementsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WidgetAgreements
            //Assert.IsInstanceOfType<WidgetAgreements> (instance, "variable 'instance' is a WidgetAgreements");
        }


        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Test]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }
        /// <summary>
        /// Test the property 'UserAgreementList'
        /// </summary>
        [Test]
        public void UserAgreementListTest()
        {
            // TODO unit test for the property 'UserAgreementList'
        }

    }

}
