/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.model.baseUris;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BaseUrisApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class BaseUrisApiTests
    {
        private BaseUrisApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BaseUrisApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BaseUrisApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' BaseUrisApi
            //Assert.IsInstanceOfType(typeof(BaseUrisApi), instance, "instance is a BaseUrisApi");
        }

        
        /// <summary>
        /// Test GetBaseUris
        /// </summary>
        [Test]
        public void GetBaseUrisTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authorization = null;
            //var response = instance.GetBaseUris(authorization);
            //Assert.IsInstanceOf<BaseUriInfo> (response, "response is BaseUriInfo");
        }
        
    }

}
