/**
*  Copyright 2019 Adobe Systems Incorporated. All rights reserved.
*  This file is licensed to you under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License. You may obtain a copy
*  of the License at http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software distributed under
*  the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
*  OF ANY KIND, either express or implied. See the License for the specific language
*  governing permissions and limitations under the License.
*
*
**/


/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.model.megaSigns
{
    /// <summary>
    /// MegaSignStateInfo
    /// </summary>
    [DataContract]
    public partial class MegaSignStateInfo :  IEquatable<MegaSignStateInfo>, IValidatableObject
    {
        /// <summary>
        /// The state to which the megaSign is to be updated. The only valid state for this variable is currently, CANCELLED
        /// </summary>
        /// <value>The state to which the megaSign is to be updated. The only valid state for this variable is currently, CANCELLED</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StateEnum
        {
            
            /// <summary>
            /// Enum CANCELLED for value: CANCELLED
            /// </summary>
            [EnumMember(Value = "CANCELLED")]
            CANCELLED = 1
        }

        /// <summary>
        /// The state to which the megaSign is to be updated. The only valid state for this variable is currently, CANCELLED
        /// </summary>
        /// <value>The state to which the megaSign is to be updated. The only valid state for this variable is currently, CANCELLED</value>
        [DataMember(Name="state", EmitDefaultValue=false)]
        public StateEnum? State { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MegaSignStateInfo" /> class.
        /// </summary>
        /// <param name="MegaSignCancellationInfo">Cancellation information for the agreement. Mandatory while cancelling a megaSign.</param>
        /// <param name="State">The state to which the megaSign is to be updated. The only valid state for this variable is currently, CANCELLED.</param>
        public MegaSignStateInfo(AgreementCancellationInfo MegaSignCancellationInfo = default(AgreementCancellationInfo), StateEnum? State = default(StateEnum?))
        {
            this.MegaSignCancellationInfo = MegaSignCancellationInfo;
            this.State = State;
        }
        
        /// <summary>
        /// Cancellation information for the agreement. Mandatory while cancelling a megaSign
        /// </summary>
        /// <value>Cancellation information for the agreement. Mandatory while cancelling a megaSign</value>
        [DataMember(Name="megaSignCancellationInfo", EmitDefaultValue=false)]
        public AgreementCancellationInfo MegaSignCancellationInfo { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MegaSignStateInfo {\n");
            sb.Append("  MegaSignCancellationInfo: ").Append(MegaSignCancellationInfo).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MegaSignStateInfo);
        }

        /// <summary>
        /// Returns true if MegaSignStateInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of MegaSignStateInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MegaSignStateInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.MegaSignCancellationInfo == input.MegaSignCancellationInfo ||
                    (this.MegaSignCancellationInfo != null &&
                    this.MegaSignCancellationInfo.Equals(input.MegaSignCancellationInfo))
                ) && 
                (
                    this.State == input.State ||
                    (this.State != null &&
                    this.State.Equals(input.State))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MegaSignCancellationInfo != null)
                    hashCode = hashCode * 59 + this.MegaSignCancellationInfo.GetHashCode();
                if (this.State != null)
                    hashCode = hashCode * 59 + this.State.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
