/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.groups;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test.model.groups
{
    /// <summary>
    ///  Class for testing GroupInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GroupInfoTests
    {
        // TODO uncomment below to declare an instance variable for GroupInfo
        //private GroupInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GroupInfo
            //instance = new GroupInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GroupInfo
        /// </summary>
        [Test]
        public void GroupInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GroupInfo
            //Assert.IsInstanceOfType<GroupInfo> (instance, "variable 'instance' is a GroupInfo");
        }


        /// <summary>
        /// Test the property 'GroupId'
        /// </summary>
        [Test]
        public void GroupIdTest()
        {
            // TODO unit test for the property 'GroupId'
        }
        /// <summary>
        /// Test the property 'GroupName'
        /// </summary>
        [Test]
        public void GroupNameTest()
        {
            // TODO unit test for the property 'GroupName'
        }

    }

}
