/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.webhooks;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WebhookMegaSignEvents
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WebhookMegaSignEventsTests
    {
        // TODO uncomment below to declare an instance variable for WebhookMegaSignEvents
        //private WebhookMegaSignEvents instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WebhookMegaSignEvents
            //instance = new WebhookMegaSignEvents();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebhookMegaSignEvents
        /// </summary>
        [Test]
        public void WebhookMegaSignEventsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WebhookMegaSignEvents
            //Assert.IsInstanceOfType<WebhookMegaSignEvents> (instance, "variable 'instance' is a WebhookMegaSignEvents");
        }


        /// <summary>
        /// Test the property 'IncludeDetailedInfo'
        /// </summary>
        [Test]
        public void IncludeDetailedInfoTest()
        {
            // TODO unit test for the property 'IncludeDetailedInfo'
        }

    }

}
