/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.libraryDocuments;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test.model.libraryDocuments
{
    /// <summary>
    ///  Class for testing LibraryDocumentCreationInfoV6
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LibraryDocumentCreationInfoV6Tests
    {
        // TODO uncomment below to declare an instance variable for LibraryDocumentCreationInfoV6
        //private LibraryDocumentCreationInfoV6 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LibraryDocumentCreationInfoV6
            //instance = new LibraryDocumentCreationInfoV6();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LibraryDocumentCreationInfoV6
        /// </summary>
        [Test]
        public void LibraryDocumentCreationInfoV6InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LibraryDocumentCreationInfoV6
            //Assert.IsInstanceOfType<LibraryDocumentCreationInfoV6> (instance, "variable 'instance' is a LibraryDocumentCreationInfoV6");
        }


        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Test]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }
        /// <summary>
        /// Test the property 'CreatorEmail'
        /// </summary>
        [Test]
        public void CreatorEmailTest()
        {
            // TODO unit test for the property 'CreatorEmail'
        }
        /// <summary>
        /// Test the property 'CreatorName'
        /// </summary>
        [Test]
        public void CreatorNameTest()
        {
            // TODO unit test for the property 'CreatorName'
        }
        /// <summary>
        /// Test the property 'FileInfos'
        /// </summary>
        [Test]
        public void FileInfosTest()
        {
            // TODO unit test for the property 'FileInfos'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ModifiedDate'
        /// </summary>
        [Test]
        public void ModifiedDateTest()
        {
            // TODO unit test for the property 'ModifiedDate'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'SharingMode'
        /// </summary>
        [Test]
        public void SharingModeTest()
        {
            // TODO unit test for the property 'SharingMode'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'TemplateTypes'
        /// </summary>
        [Test]
        public void TemplateTypesTest()
        {
            // TODO unit test for the property 'TemplateTypes'
        }

    }

}
