/**
*  Copyright 2019 Adobe Systems Incorporated. All rights reserved.
*  This file is licensed to you under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License. You may obtain a copy
*  of the License at http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software distributed under
*  the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
*  OF ANY KIND, either express or implied. See the License for the specific language
*  governing permissions and limitations under the License.
*
*
**/


/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.model.libraryDocuments
{
    /// <summary>
    /// CommonViewConfiguration
    /// </summary>
    [DataContract]
    public partial class CommonViewConfiguration :  IEquatable<CommonViewConfiguration>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CommonViewConfiguration" /> class.
        /// </summary>
        /// <param name="AutoLoginUser">Auto LogIn Flag. If true, the URL returned will automatically log the user in. If false, the URL returned will require the credentials. By default its value is false.</param>
        /// <param name="Locale">Message template locale.</param>
        /// <param name="NoChrome">No Chrome Flag. If true, the embedded page is shown without a navigation header or footer. If false, the standard page header and footer will be present. By default its value is false.</param>
        public CommonViewConfiguration(bool? AutoLoginUser = default(bool?), string Locale = default(string), bool? NoChrome = default(bool?))
        {
            this.AutoLoginUser = AutoLoginUser;
            this.Locale = Locale;
            this.NoChrome = NoChrome;
        }
        
        /// <summary>
        /// Auto LogIn Flag. If true, the URL returned will automatically log the user in. If false, the URL returned will require the credentials. By default its value is false
        /// </summary>
        /// <value>Auto LogIn Flag. If true, the URL returned will automatically log the user in. If false, the URL returned will require the credentials. By default its value is false</value>
        [DataMember(Name="autoLoginUser", EmitDefaultValue=false)]
        public bool? AutoLoginUser { get; set; }

        /// <summary>
        /// Message template locale
        /// </summary>
        /// <value>Message template locale</value>
        [DataMember(Name="locale", EmitDefaultValue=false)]
        public string Locale { get; set; }

        /// <summary>
        /// No Chrome Flag. If true, the embedded page is shown without a navigation header or footer. If false, the standard page header and footer will be present. By default its value is false
        /// </summary>
        /// <value>No Chrome Flag. If true, the embedded page is shown without a navigation header or footer. If false, the standard page header and footer will be present. By default its value is false</value>
        [DataMember(Name="noChrome", EmitDefaultValue=false)]
        public bool? NoChrome { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CommonViewConfiguration {\n");
            sb.Append("  AutoLoginUser: ").Append(AutoLoginUser).Append("\n");
            sb.Append("  Locale: ").Append(Locale).Append("\n");
            sb.Append("  NoChrome: ").Append(NoChrome).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CommonViewConfiguration);
        }

        /// <summary>
        /// Returns true if CommonViewConfiguration instances are equal
        /// </summary>
        /// <param name="input">Instance of CommonViewConfiguration to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CommonViewConfiguration input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AutoLoginUser == input.AutoLoginUser ||
                    (this.AutoLoginUser != null &&
                    this.AutoLoginUser.Equals(input.AutoLoginUser))
                ) && 
                (
                    this.Locale == input.Locale ||
                    (this.Locale != null &&
                    this.Locale.Equals(input.Locale))
                ) && 
                (
                    this.NoChrome == input.NoChrome ||
                    (this.NoChrome != null &&
                    this.NoChrome.Equals(input.NoChrome))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AutoLoginUser != null)
                    hashCode = hashCode * 59 + this.AutoLoginUser.GetHashCode();
                if (this.Locale != null)
                    hashCode = hashCode * 59 + this.Locale.GetHashCode();
                if (this.NoChrome != null)
                    hashCode = hashCode * 59 + this.NoChrome.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
