/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.baseUris;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test.model.baseUris
{
    /// <summary>
    ///  Class for testing BaseUriInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BaseUriInfoTests
    {
        // TODO uncomment below to declare an instance variable for BaseUriInfo
        //private BaseUriInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BaseUriInfo
            //instance = new BaseUriInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BaseUriInfo
        /// </summary>
        [Test]
        public void BaseUriInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BaseUriInfo
            //Assert.IsInstanceOfType<BaseUriInfo> (instance, "variable 'instance' is a BaseUriInfo");
        }


        /// <summary>
        /// Test the property 'ApiAccessPoint'
        /// </summary>
        [Test]
        public void ApiAccessPointTest()
        {
            // TODO unit test for the property 'ApiAccessPoint'
        }
        /// <summary>
        /// Test the property 'WebAccessPoint'
        /// </summary>
        [Test]
        public void WebAccessPointTest()
        {
            // TODO unit test for the property 'WebAccessPoint'
        }

    }

}
