/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.agreements;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test.model.agreements
{
    /// <summary>
    ///  Class for testing AgreementCreationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AgreementCreationResponseTests
    {
        // TODO uncomment below to declare an instance variable for AgreementCreationResponse
        //private AgreementCreationResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AgreementCreationResponse
            //instance = new AgreementCreationResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AgreementCreationResponse
        /// </summary>
        [Test]
        public void AgreementCreationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AgreementCreationResponse
            //Assert.IsInstanceOfType<AgreementCreationResponse> (instance, "variable 'instance' is a AgreementCreationResponse");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
