/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.agreements;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AgreementCreationInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AgreementCreationInfoTests
    {
        // TODO uncomment below to declare an instance variable for AgreementCreationInfo
        //private AgreementCreationInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AgreementCreationInfo
            //instance = new AgreementCreationInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AgreementCreationInfo
        /// </summary>
        [Test]
        public void AgreementCreationInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AgreementCreationInfo
            //Assert.IsInstanceOfType<AgreementCreationInfo> (instance, "variable 'instance' is a AgreementCreationInfo");
        }


        /// <summary>
        /// Test the property 'Ccs'
        /// </summary>
        [Test]
        public void CcsTest()
        {
            // TODO unit test for the property 'Ccs'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Test]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }
        /// <summary>
        /// Test the property 'DeviceInfo'
        /// </summary>
        [Test]
        public void DeviceInfoTest()
        {
            // TODO unit test for the property 'DeviceInfo'
        }
        /// <summary>
        /// Test the property 'DocumentVisibilityEnabled'
        /// </summary>
        [Test]
        public void DocumentVisibilityEnabledTest()
        {
            // TODO unit test for the property 'DocumentVisibilityEnabled'
        }
        /// <summary>
        /// Test the property 'EmailOption'
        /// </summary>
        [Test]
        public void EmailOptionTest()
        {
            // TODO unit test for the property 'EmailOption'
        }
        /// <summary>
        /// Test the property 'ExpirationTime'
        /// </summary>
        [Test]
        public void ExpirationTimeTest()
        {
            // TODO unit test for the property 'ExpirationTime'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Test]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'FileInfos'
        /// </summary>
        [Test]
        public void FileInfosTest()
        {
            // TODO unit test for the property 'FileInfos'
        }
        /// <summary>
        /// Test the property 'FirstReminderDelay'
        /// </summary>
        [Test]
        public void FirstReminderDelayTest()
        {
            // TODO unit test for the property 'FirstReminderDelay'
        }
        /// <summary>
        /// Test the property 'FormFieldLayerTemplates'
        /// </summary>
        [Test]
        public void FormFieldLayerTemplatesTest()
        {
            // TODO unit test for the property 'FormFieldLayerTemplates'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Test]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }
        /// <summary>
        /// Test the property 'MergeFieldInfo'
        /// </summary>
        [Test]
        public void MergeFieldInfoTest()
        {
            // TODO unit test for the property 'MergeFieldInfo'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ParticipantSetsInfo'
        /// </summary>
        [Test]
        public void ParticipantSetsInfoTest()
        {
            // TODO unit test for the property 'ParticipantSetsInfo'
        }
        /// <summary>
        /// Test the property 'PostSignOption'
        /// </summary>
        [Test]
        public void PostSignOptionTest()
        {
            // TODO unit test for the property 'PostSignOption'
        }
        /// <summary>
        /// Test the property 'ReminderFrequency'
        /// </summary>
        [Test]
        public void ReminderFrequencyTest()
        {
            // TODO unit test for the property 'ReminderFrequency'
        }
        /// <summary>
        /// Test the property 'SecurityOption'
        /// </summary>
        [Test]
        public void SecurityOptionTest()
        {
            // TODO unit test for the property 'SecurityOption'
        }
        /// <summary>
        /// Test the property 'SenderEmail'
        /// </summary>
        [Test]
        public void SenderEmailTest()
        {
            // TODO unit test for the property 'SenderEmail'
        }
        /// <summary>
        /// Test the property 'SignatureType'
        /// </summary>
        [Test]
        public void SignatureTypeTest()
        {
            // TODO unit test for the property 'SignatureType'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'VaultingInfo'
        /// </summary>
        [Test]
        public void VaultingInfoTest()
        {
            // TODO unit test for the property 'VaultingInfo'
        }
        /// <summary>
        /// Test the property 'WorkflowId'
        /// </summary>
        [Test]
        public void WorkflowIdTest()
        {
            // TODO unit test for the property 'WorkflowId'
        }

    }

}
