/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.agreements;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test.model.agreements
{
    /// <summary>
    ///  Class for testing DelegatedParticipantInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DelegatedParticipantInfoTests
    {
        // TODO uncomment below to declare an instance variable for DelegatedParticipantInfo
        //private DelegatedParticipantInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DelegatedParticipantInfo
            //instance = new DelegatedParticipantInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DelegatedParticipantInfo
        /// </summary>
        [Test]
        public void DelegatedParticipantInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DelegatedParticipantInfo
            //Assert.IsInstanceOfType<DelegatedParticipantInfo> (instance, "variable 'instance' is a DelegatedParticipantInfo");
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'SecurityOption'
        /// </summary>
        [Test]
        public void SecurityOptionTest()
        {
            // TODO unit test for the property 'SecurityOption'
        }

    }

}
