/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.agreements;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test.model.agreements
{
    /// <summary>
    ///  Class for testing DetailedParticipantSetInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DetailedParticipantSetInfoTests
    {
        // TODO uncomment below to declare an instance variable for DetailedParticipantSetInfo
        //private DetailedParticipantSetInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DetailedParticipantSetInfo
            //instance = new DetailedParticipantSetInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DetailedParticipantSetInfo
        /// </summary>
        [Test]
        public void DetailedParticipantSetInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DetailedParticipantSetInfo
            //Assert.IsInstanceOfType<DetailedParticipantSetInfo> (instance, "variable 'instance' is a DetailedParticipantSetInfo");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'MemberInfos'
        /// </summary>
        [Test]
        public void MemberInfosTest()
        {
            // TODO unit test for the property 'MemberInfos'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Test]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
        /// <summary>
        /// Test the property 'PrivateMessage'
        /// </summary>
        [Test]
        public void PrivateMessageTest()
        {
            // TODO unit test for the property 'PrivateMessage'
        }
        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Test]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
