/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.agreements;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FormFieldHyperlink
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FormFieldHyperlinkTests
    {
        // TODO uncomment below to declare an instance variable for FormFieldHyperlink
        //private FormFieldHyperlink instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FormFieldHyperlink
            //instance = new FormFieldHyperlink();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FormFieldHyperlink
        /// </summary>
        [Test]
        public void FormFieldHyperlinkInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FormFieldHyperlink
            //Assert.IsInstanceOfType<FormFieldHyperlink> (instance, "variable 'instance' is a FormFieldHyperlink");
        }


        /// <summary>
        /// Test the property 'DocumentLocation'
        /// </summary>
        [Test]
        public void DocumentLocationTest()
        {
            // TODO unit test for the property 'DocumentLocation'
        }
        /// <summary>
        /// Test the property 'LinkType'
        /// </summary>
        [Test]
        public void LinkTypeTest()
        {
            // TODO unit test for the property 'LinkType'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
