/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.agreements;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test.model.agreements
{
    /// <summary>
    ///  Class for testing ReminderInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReminderInfoTests
    {
        // TODO uncomment below to declare an instance variable for ReminderInfo
        //private ReminderInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReminderInfo
            //instance = new ReminderInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReminderInfo
        /// </summary>
        [Test]
        public void ReminderInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReminderInfo
            //Assert.IsInstanceOfType<ReminderInfo> (instance, "variable 'instance' is a ReminderInfo");
        }


        /// <summary>
        /// Test the property 'FirstReminderDelay'
        /// </summary>
        [Test]
        public void FirstReminderDelayTest()
        {
            // TODO unit test for the property 'FirstReminderDelay'
        }
        /// <summary>
        /// Test the property 'Frequency'
        /// </summary>
        [Test]
        public void FrequencyTest()
        {
            // TODO unit test for the property 'Frequency'
        }
        /// <summary>
        /// Test the property 'LastSentDate'
        /// </summary>
        [Test]
        public void LastSentDateTest()
        {
            // TODO unit test for the property 'LastSentDate'
        }
        /// <summary>
        /// Test the property 'NextSentDate'
        /// </summary>
        [Test]
        public void NextSentDateTest()
        {
            // TODO unit test for the property 'NextSentDate'
        }
        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Test]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }
        /// <summary>
        /// Test the property 'RecipientParticipantIds'
        /// </summary>
        [Test]
        public void RecipientParticipantIdsTest()
        {
            // TODO unit test for the property 'RecipientParticipantIds'
        }
        /// <summary>
        /// Test the property 'ReminderId'
        /// </summary>
        [Test]
        public void ReminderIdTest()
        {
            // TODO unit test for the property 'ReminderId'
        }
        /// <summary>
        /// Test the property 'StartReminderCounterFrom'
        /// </summary>
        [Test]
        public void StartReminderCounterFromTest()
        {
            // TODO unit test for the property 'StartReminderCounterFrom'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
