/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.agreements;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test.model.agreements
{
    /// <summary>
    ///  Class for testing SigningUrlSetInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SigningUrlSetInfoTests
    {
        // TODO uncomment below to declare an instance variable for SigningUrlSetInfo
        //private SigningUrlSetInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SigningUrlSetInfo
            //instance = new SigningUrlSetInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SigningUrlSetInfo
        /// </summary>
        [Test]
        public void SigningUrlSetInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SigningUrlSetInfo
            //Assert.IsInstanceOfType<SigningUrlSetInfo> (instance, "variable 'instance' is a SigningUrlSetInfo");
        }


        /// <summary>
        /// Test the property 'SigningUrlSetName'
        /// </summary>
        [Test]
        public void SigningUrlSetNameTest()
        {
            // TODO unit test for the property 'SigningUrlSetName'
        }
        /// <summary>
        /// Test the property 'SigningUrls'
        /// </summary>
        [Test]
        public void SigningUrlsTest()
        {
            // TODO unit test for the property 'SigningUrls'
        }

    }

}
