/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.agreements;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SigningUrl
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SigningUrlTests
    {
        // TODO uncomment below to declare an instance variable for SigningUrl
        //private SigningUrl instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SigningUrl
            //instance = new SigningUrl();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SigningUrl
        /// </summary>
        [Test]
        public void SigningUrlInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SigningUrl
            //Assert.IsInstanceOfType<SigningUrl> (instance, "variable 'instance' is a SigningUrl");
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'EsignUrl'
        /// </summary>
        [Test]
        public void EsignUrlTest()
        {
            // TODO unit test for the property 'EsignUrl'
        }

    }

}
