/**
*  Copyright 2019 Adobe Systems Incorporated. All rights reserved.
*  This file is licensed to you under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License. You may obtain a copy
*  of the License at http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software distributed under
*  the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
*  OF ANY KIND, either express or implied. See the License for the specific language
*  governing permissions and limitations under the License.
*
*
**/


/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.model.agreements
{
    /// <summary>
    /// FileUploadOptions
    /// </summary>
    [DataContract]
    public partial class FileUploadOptions :  IEquatable<FileUploadOptions>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FileUploadOptions" /> class.
        /// </summary>
        /// <param name="LibraryDocument">Whether library documents link should appear or not. Default value is taken as true.</param>
        /// <param name="LocalFile">Whether local file upload button should appear or not. Default value is taken as true.</param>
        /// <param name="WebConnectors">Whether link to attach documents from web sources like Dropbox should appear or not. Default value is taken as true.</param>
        public FileUploadOptions(bool? LibraryDocument = default(bool?), bool? LocalFile = default(bool?), bool? WebConnectors = default(bool?))
        {
            this.LibraryDocument = LibraryDocument;
            this.LocalFile = LocalFile;
            this.WebConnectors = WebConnectors;
        }
        
        /// <summary>
        /// Whether library documents link should appear or not. Default value is taken as true
        /// </summary>
        /// <value>Whether library documents link should appear or not. Default value is taken as true</value>
        [DataMember(Name="libraryDocument", EmitDefaultValue=false)]
        public bool? LibraryDocument { get; set; }

        /// <summary>
        /// Whether local file upload button should appear or not. Default value is taken as true
        /// </summary>
        /// <value>Whether local file upload button should appear or not. Default value is taken as true</value>
        [DataMember(Name="localFile", EmitDefaultValue=false)]
        public bool? LocalFile { get; set; }

        /// <summary>
        /// Whether link to attach documents from web sources like Dropbox should appear or not. Default value is taken as true
        /// </summary>
        /// <value>Whether link to attach documents from web sources like Dropbox should appear or not. Default value is taken as true</value>
        [DataMember(Name="webConnectors", EmitDefaultValue=false)]
        public bool? WebConnectors { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FileUploadOptions {\n");
            sb.Append("  LibraryDocument: ").Append(LibraryDocument).Append("\n");
            sb.Append("  LocalFile: ").Append(LocalFile).Append("\n");
            sb.Append("  WebConnectors: ").Append(WebConnectors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FileUploadOptions);
        }

        /// <summary>
        /// Returns true if FileUploadOptions instances are equal
        /// </summary>
        /// <param name="input">Instance of FileUploadOptions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FileUploadOptions input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LibraryDocument == input.LibraryDocument ||
                    (this.LibraryDocument != null &&
                    this.LibraryDocument.Equals(input.LibraryDocument))
                ) && 
                (
                    this.LocalFile == input.LocalFile ||
                    (this.LocalFile != null &&
                    this.LocalFile.Equals(input.LocalFile))
                ) && 
                (
                    this.WebConnectors == input.WebConnectors ||
                    (this.WebConnectors != null &&
                    this.WebConnectors.Equals(input.WebConnectors))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LibraryDocument != null)
                    hashCode = hashCode * 59 + this.LibraryDocument.GetHashCode();
                if (this.LocalFile != null)
                    hashCode = hashCode * 59 + this.LocalFile.GetHashCode();
                if (this.WebConnectors != null)
                    hashCode = hashCode * 59 + this.WebConnectors.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
