/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.users;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserView
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserViewTests
    {
        // TODO uncomment below to declare an instance variable for UserView
        //private UserView instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserView
            //instance = new UserView();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserView
        /// </summary>
        [Test]
        public void UserViewInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserView
            //Assert.IsInstanceOfType<UserView> (instance, "variable 'instance' is a UserView");
        }


        /// <summary>
        /// Test the property 'EmbeddedCode'
        /// </summary>
        [Test]
        public void EmbeddedCodeTest()
        {
            // TODO unit test for the property 'EmbeddedCode'
        }
        /// <summary>
        /// Test the property 'Expiration'
        /// </summary>
        [Test]
        public void ExpirationTest()
        {
            // TODO unit test for the property 'Expiration'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
