/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.widgets;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ParticipantSecurityOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ParticipantSecurityOptionTests
    {
        // TODO uncomment below to declare an instance variable for ParticipantSecurityOption
        //private ParticipantSecurityOption instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ParticipantSecurityOption
            //instance = new ParticipantSecurityOption();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ParticipantSecurityOption
        /// </summary>
        [Test]
        public void ParticipantSecurityOptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ParticipantSecurityOption
            //Assert.IsInstanceOfType<ParticipantSecurityOption> (instance, "variable 'instance' is a ParticipantSecurityOption");
        }


        /// <summary>
        /// Test the property 'AuthenticationMethod'
        /// </summary>
        [Test]
        public void AuthenticationMethodTest()
        {
            // TODO unit test for the property 'AuthenticationMethod'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'PhoneInfo'
        /// </summary>
        [Test]
        public void PhoneInfoTest()
        {
            // TODO unit test for the property 'PhoneInfo'
        }

    }

}
