/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.widgets;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WidgetView
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WidgetViewTests
    {
        // TODO uncomment below to declare an instance variable for WidgetView
        //private WidgetView instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WidgetView
            //instance = new WidgetView();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WidgetView
        /// </summary>
        [Test]
        public void WidgetViewInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WidgetView
            //Assert.IsInstanceOfType<WidgetView> (instance, "variable 'instance' is a WidgetView");
        }


        /// <summary>
        /// Test the property 'EmbeddedCode'
        /// </summary>
        [Test]
        public void EmbeddedCodeTest()
        {
            // TODO unit test for the property 'EmbeddedCode'
        }
        /// <summary>
        /// Test the property 'Expiration'
        /// </summary>
        [Test]
        public void ExpirationTest()
        {
            // TODO unit test for the property 'Expiration'
        }
        /// <summary>
        /// Test the property 'IsCurrent'
        /// </summary>
        [Test]
        public void IsCurrentTest()
        {
            // TODO unit test for the property 'IsCurrent'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
