/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.transientDocuments;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test.model.transientDocuments
{
    /// <summary>
    ///  Class for testing TransientDocumentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TransientDocumentResponseTests
    {
        // TODO uncomment below to declare an instance variable for TransientDocumentResponse
        //private TransientDocumentResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransientDocumentResponse
            //instance = new TransientDocumentResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransientDocumentResponse
        /// </summary>
        [Test]
        public void TransientDocumentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TransientDocumentResponse
            //Assert.IsInstanceOfType<TransientDocumentResponse> (instance, "variable 'instance' is a TransientDocumentResponse");
        }


        /// <summary>
        /// Test the property 'TransientDocumentId'
        /// </summary>
        [Test]
        public void TransientDocumentIdTest()
        {
            // TODO unit test for the property 'TransientDocumentId'
        }

    }

}
