/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.megaSigns;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test.model.megaSigns
{
    /// <summary>
    ///  Class for testing ChildAgreementsInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChildAgreementsInfoTests
    {
        // TODO uncomment below to declare an instance variable for ChildAgreementsInfo
        //private ChildAgreementsInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChildAgreementsInfo
            //instance = new ChildAgreementsInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChildAgreementsInfo
        /// </summary>
        [Test]
        public void ChildAgreementsInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChildAgreementsInfo
            //Assert.IsInstanceOfType<ChildAgreementsInfo> (instance, "variable 'instance' is a ChildAgreementsInfo");
        }


        /// <summary>
        /// Test the property 'FileInfo'
        /// </summary>
        [Test]
        public void FileInfoTest()
        {
            // TODO unit test for the property 'FileInfo'
        }

    }

}
