/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.megaSigns;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test.model.megaSigns
{
    /// <summary>
    ///  Class for testing MegaSignChildAgreementsFileInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MegaSignChildAgreementsFileInfoTests
    {
        // TODO uncomment below to declare an instance variable for MegaSignChildAgreementsFileInfo
        //private MegaSignChildAgreementsFileInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MegaSignChildAgreementsFileInfo
            //instance = new MegaSignChildAgreementsFileInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MegaSignChildAgreementsFileInfo
        /// </summary>
        [Test]
        public void MegaSignChildAgreementsFileInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MegaSignChildAgreementsFileInfo
            //Assert.IsInstanceOfType<MegaSignChildAgreementsFileInfo> (instance, "variable 'instance' is a MegaSignChildAgreementsFileInfo");
        }


        /// <summary>
        /// Test the property 'ChildAgreementsInfoFileId'
        /// </summary>
        [Test]
        public void ChildAgreementsInfoFileIdTest()
        {
            // TODO unit test for the property 'ChildAgreementsInfoFileId'
        }
        /// <summary>
        /// Test the property 'FileType'
        /// </summary>
        [Test]
        public void FileTypeTest()
        {
            // TODO unit test for the property 'FileType'
        }
        /// <summary>
        /// Test the property 'TransientDocumentId'
        /// </summary>
        [Test]
        public void TransientDocumentIdTest()
        {
            // TODO unit test for the property 'TransientDocumentId'
        }

    }

}
