/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.megaSigns;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test.model.megaSigns
{
    /// <summary>
    ///  Class for testing MegaSignChildAgreements
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MegaSignChildAgreementsTests
    {
        // TODO uncomment below to declare an instance variable for MegaSignChildAgreements
        //private MegaSignChildAgreements instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MegaSignChildAgreements
            //instance = new MegaSignChildAgreements();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MegaSignChildAgreements
        /// </summary>
        [Test]
        public void MegaSignChildAgreementsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MegaSignChildAgreements
            //Assert.IsInstanceOfType<MegaSignChildAgreements> (instance, "variable 'instance' is a MegaSignChildAgreements");
        }


        /// <summary>
        /// Test the property 'MegaSignChildAgreementList'
        /// </summary>
        [Test]
        public void MegaSignChildAgreementListTest()
        {
            // TODO unit test for the property 'MegaSignChildAgreementList'
        }
        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Test]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }

    }

}
