/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.model.webhooks;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WebhookConditionalParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WebhookConditionalParamsTests
    {
        // TODO uncomment below to declare an instance variable for WebhookConditionalParams
        //private WebhookConditionalParams instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WebhookConditionalParams
            //instance = new WebhookConditionalParams();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebhookConditionalParams
        /// </summary>
        [Test]
        public void WebhookConditionalParamsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WebhookConditionalParams
            //Assert.IsInstanceOfType<WebhookConditionalParams> (instance, "variable 'instance' is a WebhookConditionalParams");
        }


        /// <summary>
        /// Test the property 'WebhookAgreementEvents'
        /// </summary>
        [Test]
        public void WebhookAgreementEventsTest()
        {
            // TODO unit test for the property 'WebhookAgreementEvents'
        }
        /// <summary>
        /// Test the property 'WebhookLibraryDocumentEvents'
        /// </summary>
        [Test]
        public void WebhookLibraryDocumentEventsTest()
        {
            // TODO unit test for the property 'WebhookLibraryDocumentEvents'
        }
        /// <summary>
        /// Test the property 'WebhookMegaSignEvents'
        /// </summary>
        [Test]
        public void WebhookMegaSignEventsTest()
        {
            // TODO unit test for the property 'WebhookMegaSignEvents'
        }
        /// <summary>
        /// Test the property 'WebhookWidgetEvents'
        /// </summary>
        [Test]
        public void WebhookWidgetEventsTest()
        {
            // TODO unit test for the property 'WebhookWidgetEvents'
        }

    }

}
